// React-Angular/apps/react-app/src/App.tsx
import React from 'react';
import { Routes, Route, Link, useLocation } from 'react-router-dom';
import { Typography } from '@mlp/react';
import Dashboard from './components/Dashboard';
import LimitMonitor from './components/LimitMonitor';
import { FormExample } from './components/FormExample';
import { UserRegistration } from './components/UserRegistration';
import './App.scss';

function App() {
  const location = useLocation();

  return (
    <div className="app-container">
      <header className="app-header">
        <Typography.Title level={1} style={{ color: 'white', margin: 0 }}>
          MLP Framework Demo - React
        </Typography.Title>
        <Typography.Text style={{ color: 'white', opacity: 0.9, margin: 0 }}>
          Framework-agnostic MVVM with React bindings
        </Typography.Text>
      </header>
      
      <nav className="app-nav">
        <Link 
          to="/" 
          className={location.pathname === '/' ? 'active' : ''}
        >
          Dashboard
        </Link>
        <Link 
          to="/limit-monitor" 
          className={location.pathname === '/limit-monitor' ? 'active' : ''}
        >
          Limit Monitor
        </Link>
        <Link 
          to="/form-example" 
          className={location.pathname === '/form-example' ? 'active' : ''}
        >
          Form Example
        </Link>
        <Link 
          to="/user-registration" 
          className={location.pathname === '/user-registration' ? 'active' : ''}
        >
          User Registration
        </Link>
      </nav>
      
      <main className="app-main">
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/limit-monitor" element={<LimitMonitor />} />
          <Route path="/form-example" element={<FormExample />} />
          <Route path="/user-registration" element={<UserRegistration />} />
        </Routes>
      </main>
    </div>
  );
}

export default App;

// React-Angular/apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  styleUrls: ['./app.component.scss'],
  template: `
    <div class="app-container">
      <header class="app-header">
        <h1>MLP Framework Demo - Angular</h1>
        <p>Framework-agnostic MVVM with Angular bindings</p>
      </header>
      
      <nav class="app-nav">
        <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
        <a routerLink="/limit-monitor" routerLinkActive="active">Limit Monitor</a>
        <a routerLink="/form-example" routerLinkActive="active">Form Example</a>
        <a routerLink="/user-registration" routerLinkActive="active">User Registration</a>
      </nav>
      
      <main class="app-main">
        <router-outlet></router-outlet>
      </main>
    </div>
  `
})
export class AppComponent {
  title = 'angular-app';
}
