// React-Angular/apps/angular-app/src/app/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzSpaceModule, NzSpaceItemDirective } from 'ng-zorro-antd/space';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzListModule } from 'ng-zorro-antd/list';
import { DashboardViewModel } from './DashboardViewModel';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    NzCardModule,
    NzButtonModule,
    NzSpaceModule,
    NzSpaceItemDirective,
    NzAlertModule,
    NzListModule
  ],
  styleUrls: ['./dashboard.component.scss'],
  template: `
    <div class="page-container">
      <div  style="display: none;"></div>
      <h2 class="page-title">Dashboard</h2>

      <nz-card 
        nzTitle="Counter Example" 
        nzExtra="MLP Framework Demo"
        class="ant-card">
        
        <div class="counter-display">
          <h1 class="counter-value">
            <span>Count:{{Date.now()}}</span>
            Count: {{ viewModel.model.counter }}
          </h1>
        </div>
        
        <nz-space nzSize="middle" class="button-group">
          <button 
            *nzSpaceItem
            nz-button 
            nzType="primary"
            nzSize="large"
            nz-icon="plus"
            (click)="viewModel.incrementCommand.execute()"
            [disabled]="!viewModel.incrementCommand.canExecute()"
            [nzLoading]="viewModel.model.isLoading">
            Increment
          </button>
          
          <button 
            *nzSpaceItem
            nz-button 
            nzSize="large"
            nz-icon="minus"
            (click)="viewModel.decrementCommand.execute()"
            [disabled]="!viewModel.decrementCommand.canExecute()"
            [nzLoading]="viewModel.model.isLoading">
            Decrement
          </button>
          
          <button 
            *nzSpaceItem
            nz-button 
            nzSize="large"
            nz-icon="reload"
            (click)="viewModel.resetCommand.execute()"
            [disabled]="!viewModel.resetCommand.canExecute()"
            [nzLoading]="viewModel.model.isLoading">
            Reset
          </button>
        </nz-space>
        
        <nz-alert 
          [style.display]="viewModel.model.message ? 'block' : 'none'"
          nzType="success"
          nzMessage="{{ viewModel.model.message }}"
          nzIcon="check-circle"
          class="ant-alert">
        </nz-alert>
        
        <nz-alert 
          [style.display]="viewModel.model.error ? 'block' : 'none'"
          nzType="error"
          nzMessage="{{ viewModel.model.error }}"
          nzIcon="exclamation-circle"
          class="ant-alert">
        </nz-alert>
      </nz-card>
      
      <nz-card 
        nzTitle="Framework Information"
        class="ant-card">
        
        <nz-list nzSize="small" class="info-list">
          <nz-list-item>
            <strong>Framework:</strong> Angular 18
          </nz-list-item>
          <nz-list-item>
            <strong>UI Library:</strong> Ant Design (ng-zorro-antd)
          </nz-list-item>
          <nz-list-item>
            <strong>MVVM Library:</strong> &#64;mlp/core + &#64;mlp/angular
          </nz-list-item>
          <nz-list-item>
            <strong>Build Tool:</strong> Angular DevKit Build-Angular
          </nz-list-item>
        </nz-list>
      </nz-card>
    </div>
  `
})
export class DashboardComponent {
  viewModel = new DashboardViewModel();
}

// React-Angular/apps/react-app/src/components/Dashboard.tsx
import React, { useMemo } from 'react';
import { useViewModel } from '@mlp/react';
import { 
  Card, 
  Button, 
  Space, 
  Typography, 
  Alert, 
  Spin,
  PlusOutlined,
  MinusOutlined,
  ReloadOutlined,
  CheckCircleOutlined,
  ExclamationCircleOutlined
} from '@mlp/react';
import { DashboardViewModel } from './DashboardViewModel';
import './Dashboard.scss';

const Dashboard: React.FC = () => {
  const viewModel = useViewModel(useMemo(() => new DashboardViewModel(), []))

  return (
    <div className="react-page-container">
      <Typography.Title level={2} className="react-page-title">
        Dashboard
      </Typography.Title>

      <Card 
        title="Counter Example" 
        extra="MLP Framework Demo"
        className="ant-card"
      >
        <div className="counter-display">
          <Typography.Title level={1} className="counter-value">
            Count: {viewModel.model.counter}
          </Typography.Title>
        </div>
        
        <Space size="middle" className="react-button-group">
          <Button 
            type="primary"
            size="large"
            icon={<PlusOutlined />}
            onClick={() => viewModel.incrementCommand.execute()}
            disabled={!viewModel.incrementCommand.canExecute()}
            loading={viewModel.model.isLoading}
          >
            Increment
          </Button>
          
          <Button 
            size="large"
            icon={<MinusOutlined />}
            onClick={() => viewModel.decrementCommand.execute()}
            disabled={!viewModel.decrementCommand.canExecute()}
            loading={viewModel.model.isLoading}
          >
            Decrement
          </Button>
          
          <Button 
            type="dashed"
            size="large"
            icon={<ReloadOutlined />}
            onClick={() => viewModel.resetCommand.execute()}
            disabled={!viewModel.resetCommand.canExecute()}
            loading={viewModel.model.isLoading}
          >
            Reset
          </Button>
        </Space>
        
        {viewModel.model.message && (
          <Alert
            type="success"
            message={viewModel.model.message}
            icon={<CheckCircleOutlined />}
            showIcon
            className="ant-alert"
          />
        )}
        
        {viewModel.model.error && (
          <Alert
            type="error"
            message={viewModel.model.error}
            icon={<ExclamationCircleOutlined />}
            showIcon
            className="ant-alert"
          />
        )}
      </Card>
      
      <Card 
        title="Framework Information"
        className="ant-card"
      >
        <div className="info-list">
          <div className="info-item">
            <Typography.Text strong>Framework:</Typography.Text> React 18
          </div>
          <div className="info-item">
            <Typography.Text strong>UI Library:</Typography.Text> Ant Design
          </div>
          <div className="info-item">
            <Typography.Text strong>MVVM Library:</Typography.Text> @mlp/core + @mlp/react
          </div>
          <div className="info-item">
            <Typography.Text strong>Build Tool:</Typography.Text> Vite
          </div>
        </div>
      </Card>
    </div>
  );
};

export default Dashboard;
